version: "3"
services:
        redis:
                image: "redis:alpine"
                expose:
                        - 6379
        server:
                build: ./server
                image: heaty566/myquiz-v2-server:latest
                ports:
                        - 4000:4000
                env_file:
                        - ./data-dev/config/server.env
