version: "3"
services:
        server:
                env_file:
                        - ./dev/config/server.env
                image: heaty566/my-chess-server:1.0.2
                build: ./server
                expose:
                        - 4000
