version: "3"
services:
        redis:
                image: "redis:alpine"
                expose:
                        - 6379
        server:
                image: heaty566/my-game-server:latest
                expose:
                        - 4000
                env_file:
                        - ./data/config/server.env
        client:
                image: heaty566/my-game-client:latest
                expose:
                        - 3000
        certbot:
                image: certbot/certbot
                restart: unless-stopped
                volumes:
                        - ./data/certbot/conf:/etc/letsencrypt
                        - ./data/certbot/www:/var/www/certbot
                entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        nginx:
                image: nginx:1.15-alpine
                restart: unless-stopped
                ports:
                        - 80:80
                        - 443:443
                volumes:
                        - ./data/certbot/conf:/etc/letsencrypt
                        - ./data/certbot/www:/var/www/certbot
                        - ./data/nginx:/etc/nginx/conf.d
                command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
