version: "3"
services:
        redis:
                image: redis
                ports:
                        - 7000:6379
        client:
                image: heaty566/my-chess-client:latest
                ports:
                        - 3000:3000
