version: "3"
services:
        redis:
                image: "redis:alpine"
                expose:
                        - 6379
        server:
                image: heaty566/my-game-server:latest
                ports:
                        - 4000:4000
                env_file:
                        - ./config/server.env
        mysqldb:
                image: mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: 123456
                        MYSQL_DATABASE: mygame
                ports:
                        - 3366:3306
