name: auto-build-deploy

on:
        push:
                branches:
                        - "main"
jobs:
        hello:
                runs-on: ubuntu-latest
                steps:
                        - name: executing remote ssh commands using ssh key
                          run: |
                                  if [ -n ${{secrets.PASSWORD}} ] then
                                    echo 'ready to deploy'
                                  else 
                                    echo 'not ready'
                                    exit
                                  fi
        test:
                runs-on: ubuntu-latest
                steps:
                        - name: executing remote ssh commands using ssh key
                          uses: appleboy/ssh-action@master
                          with:
                                  host: ${{ secrets.HOST }}
                                  username: ${{ secrets.USERNAME }}
                                  password: ${{ secrets.PASSWORD }}
                                  port: ${{ secrets.PORT }}
                                  script: pwd
