name: auto-build-deploy

on:
        push:
                branches:
                        - "main"
jobs:
        test:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout
                          uses: actions/checkout@v2
                        - name: Login Docker Hub
                          uses: docker/login-action@v1
                          with:
                                  username: ${{ secrets.DOCKER_USERNAME }}
                                  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
                        - name: Set up Docker Buildx
                          uses: docker/setup-buildx-action@v1
                          id: buildx
                        - name: Build and Push for Server
                          uses: docker/build-push-action@v2
                          id: docker_build_server
                          with:
                                  context: ./server
                                  file: ./server/Dockerfile
                                  builder: ${{steps.buildx.outputs.name}}
                                  push: true
                                  tags: heaty566/my-game-server:latest
                        - name: Build and Push for Client
                          uses: docker/build-push-action@v2
                          id: docker_build_server
                          with:
                                  context: ./client
                                  file: ./client/Dockerfile
                                  builder: ${{steps.buildx.outputs.name}}
                                  push: true
                                  tags: heaty566/my-game-server:latest
                        - name: Verify
                          run: |
                                  echo ${{steps.docker_build_server.outputs.digest}}
                                  echo ${{steps.client.outputs.digest}}
                                  echo 'Build done, ready to deploy'
