name: auto-deploy

on:
        push:
                branches:
                        - "main"
jobs:
        test:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout
                          uses: actions/checkout@v2
                        - name: Login Docker Hub
                          uses: docker/login-action@v1
                          with:
                                  username: ${{ secrets.DOCKER_USERNAME }}
                                  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
