name: auto-deploy

on:
        push:
                branches:
                        - "main"
jobs:
        test:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout
                          uses: actions/checkout@v2
                        - name: Login Docker Hub
                          uses: docker/login-action@v1
                          with:
                                  username: ${{ secrets.DOCKER_USERNAME }}
                                  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
                        - name: Set up Docker Buildx
                          uses: docker/setup-buildx-action@v1
                          id: buildx
                        - name: Build and Push
                          uses: docker/build-push-action@v2
                          id: docker_build
                          with:
                                  context: ./server
                                  file: ./Dockerfile
                                  builder: ${{steps.buildx.outputs.name}}
                                  push: true
                                  tags: user/my-game-server:latest

                        - name: Verify
                          run: echo ${{steps.docker_build.outputs.digest}}
